### ISSUE TITLE
说好的unity呢

### ISSUE THREAD

**Issue by hustanhuang** [Mauriyin/ChineseMap#1]
。。。最后还是qt了啊

**Comment by Mauriyin** [comment]
蛤，有unity版啊，MapOfChina是Unity版，qt是帮别人改的😂发自网易邮箱大师
            在2017年02月28日 23:41，Andrew Huang 写道： 。。。最后还是qt了啊

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Mauriyin/ChineseMap","title":"Mauriyin/ChineseMap","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Mauriyin/ChineseMap"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"说好的unity呢 (#1)"}],"action":{"name":"View Issue","url":"https://github.com/Mauriyin/ChineseMap/issues/1"}}}
